### PR TITLE
Sago anti crash

### PR DESCRIPTION
**Pull request by sago007**
I have made a bunch of changes to make the game more portable. This was mainly to find other Linux 64 bit problems but I might have found the https://github.com/OpenArena/engine/issues/4 bug as well.

### CODE REVIEW

**Comment by sago007** [comment]
Looks like I have hit a problem with my local compiler defaulting to C99 and Travis compiling in C89 mode.

Are there any other compilers that will have trouble with C99? (I am mainly thinking about Microsoft compilers here). @leilei- what compiler do you use?

While the VM code is forced to C89 due to the qvm compiler the engine could benefit greatly from a newer, more reliable standard.

**Comment by sago007** [comment]
I tried changing the C standard choice to "gnu99". It does allow more modern and safer approaches to problems but it depends on the weakest compiler in the chain. I don't know if there is an Windows 9x compiler that supports it for instance.

**Comment by leilei-** [comment]
Just compiled it (the newly pushed into engine revision) and tested on Windows 95, it still works fine as intended.  :+1:

**Comment by sago007** [comment]
Travis uses GCC 4.6.3 so it seems all good. I'll merge it.

**Pull request merged**
