### PR TITLE
Add a description how to build & run the game on modern macOS

### PR DESCRIPTION
**Pull request by cubuspl42**
I know that these steps are hacky and non-perfect, but it's better to note down what works at all, so someone with proper knowledge can provide a better solution.

### CODE REVIEW

**Comment by NeonKnightOA** [comment]
Tagging @sago007

**Comment by sago007** [comment]
I tried using this on my Mac after a couple of days letting my old Mac Mini update itself to 12.3.

```
brew install sdl libxmp
./make-macosx.sh x86_64
```


I also added "SDL_VERSION=1" to Makefile.local to avoid the recent commit.

It just failed with:
```
malformed universal file: slice content is not mach-o or a static library file 'code/libs/macosx/libSDL-1.2.0.dylib'
```

You did not have this problem?

**Comment by cubuspl42** [comment]
No, I didn't do any tricks with `"SDL_VERSION=1"`. You can see which commit I'm basing on [here](https://github.com/cubuspl42/OpenArena-engine/commits/readme-macos).

What's that path `code/libs/macosx/`? It looks suspicious.

**Comment by cubuspl42** [comment]
Closing as there's no movement here

**Comment by cubuspl42** [comment]
I created a new bundle, which fixed a new issue I recently encountered: https://github.com/cubuspl42/OpenArena-engine/releases/tag/v0.0.1-fix2

**Comment by The-Gig** [comment]
This seems interesting... Unfortunately, I don't have a Mac to perform any testing...

**Pull request closed without merging**
