### PR TITLE
Upstream sync

### PR DESCRIPTION
**Pull request by sago007**
This is a complete merge of ioqauke3 as it looks now.

I have tested it on my machine and it works great.
I have tested a bit of single player, multi player on an old server and ensured that colour 8 still works.

The reason I want to sync this is that I plan to create a builder that regularly builds the Windows and Linux binaries and I wanted an updated Makefile before starting as the old Windows cross compile was semi broken. 

However I cannot test the effect this has on @leilei- 's latest changes. So if @leilei- could test this before the pull request is accepted then it would be great.

### CODE REVIEW

**Comment by leilei-** [comment]
Quick testing right now
- the eyes works
- the atlases work
- allt he crazy postprocess stuff works
- the virtualmode works
- Windows 95 works
- Mod playback works

**Comment by leilei-** [comment]
Looks like i'm getting compiler errors 
```
DED_CC code/sys/sys_win32.c
DED_CC code/sys/con_win32.c
LD build/release-mingw32-x86/oa_ded.x86.exe
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x2f8): undefined referen
ce to `getservbyport@8'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x37d): undefined referen
ce to `gethostbyaddr@12'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3f1): undefined referen
ce to `inet_ntoa@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x403): undefined referen
ce to `ntohs@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x437): undefined referen
ce to `WSAGetLastError@0'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x501): undefined referen
ce to `WSASetLastError@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x9c0): undefined referen
ce to `htons@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x9f1): undefined referen
ce to `getservbyname@8'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0xa23): undefined referen
ce to `htonl@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0xc7f): undefined referen
ce to `gethostbyname@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0xddb): undefined referen
ce to `inet_addr@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0xe08): undefined referen
ce to `getservbyname@8'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0xe24): undefined referen
ce to `inet_ntoa@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0xe82): undefined referen
ce to `WSAGetLastError@0'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x1017): undefined refere
nce to `inet_addr@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x10e4): undefined refere
nce to `gethostbyname@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x11e1): undefined refere
nce to `WSAGetLastError@0'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x1312): undefined refere
nce to `gethostbyname@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x1473): undefined refere
nce to `WSAGetLastError@0'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x1604): undefined refere
nce to `WSAGetLastError@0'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x1d9a): undefined refere
nce to `WSASetLastError@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x2040): undefined refere
nce to `ntohs@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x20dc): undefined refere
nce to `ntohs@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x226a): undefined refere
nce to `__WSAFDIsSet@8'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x228a): undefined refere
nce to `__WSAFDIsSet@8'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x22b2): undefined refere
nce to `__WSAFDIsSet@8'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x230a): undefined refere
nce to `recvfrom@24'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x2392): undefined refere
nce to `recvfrom@24'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x24aa): undefined refere
nce to `recvfrom@24'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x25d1): undefined refere
nce to `WSAGetLastError@0'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x2608): undefined refere
nce to `WSAGetLastError@0'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x2641): undefined refere
nce to `WSAGetLastError@0'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x2771): undefined refere
nce to `WSASetLastError@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x2b0c): undefined refere
nce to `sendto@24'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x2b1b): undefined refere
nce to `WSAGetLastError@0'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x2bbc): undefined refere
nce to `sendto@24'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x2c6d): undefined refere
nce to `sendto@24'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x2eec): undefined refere
nce to `WSASetLastError@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x2f9c): undefined refere
nce to `gethostname@8'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x2ffc): undefined refere
nce to `WSASetLastError@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x373d): undefined refere
nce to `socket@12'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3763): undefined refere
nce to `ioctlsocket@12'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3795): undefined refere
nce to `setsockopt@20'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x37d7): undefined refere
nce to `htons@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x37f1): undefined refere
nce to `bind@12'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3826): undefined refere
nce to `WSAGetLastError@0'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3833): undefined refere
nce to `closesocket@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3843): undefined refere
nce to `WSAGetLastError@0'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x395e): undefined refere
nce to `socket@12'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3984): undefined refere
nce to `ioctlsocket@12'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x39a0): undefined refere
nce to `in6addr_any'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x39b0): undefined refere
nce to `in6addr_any'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x39b9): undefined refere
nce to `in6addr_any'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x39c2): undefined refere
nce to `in6addr_any'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x39ec): undefined refere
nce to `bind@12'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3a31): undefined refere
nce to `htons@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3a41): undefined refere
nce to `WSAGetLastError@0'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3a7d): undefined refere
nce to `WSAGetLastError@0'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3a8b): undefined refere
nce to `closesocket@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3c47): undefined refere
nce to `setsockopt@20'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3c7f): undefined refere
nce to `setsockopt@20'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3ca1): undefined refere
nce to `ntohs@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3d14): undefined refere
nce to `closesocket@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3d69): undefined refere
nce to `closesocket@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3da4): undefined refere
nce to `setsockopt@20'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3de5): undefined refere
nce to `socket@12'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3e00): undefined refere
nce to `gethostbyname@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3e68): undefined refere
nce to `htons@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3e8b): undefined refere
nce to `connect@12'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3ee8): undefined refere
nce to `send@16'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3f13): undefined refere
nce to `recv@16'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3f9b): undefined refere
nce to `htons@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3fc2): undefined refere
nce to `send@16'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x3fed): undefined refere
nce to `recv@16'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x4131): undefined refere
nce to `send@16'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x415c): undefined refere
nce to `recv@16'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x4a42): undefined refere
nce to `closesocket@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x4a69): undefined refere
nce to `closesocket@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x4a86): undefined refere
nce to `closesocket@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x4aa3): undefined refere
nce to `closesocket@4'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x4b63): undefined refere
nce to `WSAStartup@8'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x4be0): undefined refere
nce to `WSACleanup@0'
build/release-mingw32-x86/ded/net_ip.o:net_ip.c:(.text+0x4dd6): undefined refere
nce to `select@20'
build/release-mingw32-x86/ded/sys_win32.o:sys_win32.c:(.text+0x24e): undefined r
eference to `timeGetTime@0'
build/release-mingw32-x86/ded/sys_win32.o:sys_win32.c:(.text+0x262): undefined r
eference to `timeGetTime@0'
```

**Comment by leilei-** [comment]
Quick testing, shows there's more bugs, likely related to the SDL2 changes:
- After vid_restart, the player permanently turns left until map change
- SDL2 breaks Windows 9X support, crash related to its use of AttachConsole
- SDL2.dll is 4.5mb, which is unacceptably big. SDL2.dll in the devel-2.0.4 zip is 1mb

**Comment by leilei-** [comment]
Maybe this could be pulled over the SDL2 branch instead until something's figured out with windows SDL1 support

**Comment by sago007** [comment]
I feared this.
I looked at it about a month ago to see what it would take to fix the Windows cross compile build (getting libcurl to work again). 
It was at that time I noticed that the difference in the Makefile was significant and I really wanted to sync it before doing anything. Having two branches living separately for a significantly amount of time is bad. However I did not follow through at the time. 

I when read that you had restored Win 95 support and I got scared. It seemed like something that would make a sync significantly harder. I therefore started the sync. I hoped that getting it done sooner than later would allow you to work your magic before forgetting what it took to get it working.

I don't think there is any point ifdefing the SDL2. While none of the cool features of SDL2 is used at the moment, I believe that at some point SDL2's gamecontroller support will be introduced... and it is a vastly improvement over the old joypad support because it can be made to work "out-of-the-box". 

I fear that the overhead of sticking to an old version of 1.2 or doing it manually will only get significantly harder as time progresses and hold the project back. I also fear that at one point we cannot get new architectures to work and I fear that some of the really cool features you added will be unportable at that time. 

But it is your decision and if you say that we stick to SDL 1.2 I'll just go ahead and fix cross-compiling in the current master.

**Comment by KuehnhammerTobias** [comment]
@sago007: your ioquake merge will push OA forward a lot! Great job! Can/will you create a seperate OA fork? OA2? OA+? Or will you merge your changes into your existing repository OAX?
To me there are also too much 'blockers' that will hold back OA development (e.g.: Win95, SDL 1.2 etc.). I'm highly interested in your ioquake merge :thumbsup:

**Comment by leilei-** [comment]
Win95 and SDL 1.2 isn't holding back any development.

**Comment by sago007** [comment]
I have created a merge into the SDL2 branch instead. Closing this.

**Pull request closed without merging**
